# Introduction to R
Topics covered in this lecture

- Introduction to R and RStudio
- Data Management
- Plotting and Graphs with R
- Basic Statistics

In-class exercises will be conducted throughout the Lecture.

## Online Resources and Help
Very large user community for R. Google search for ``Some topic R'' usually leads quickly to the desired help.
Here are the links to a few online tutorials

- [UCLA Institute for Digital Research and Education](http://stats.idre.ucla.edu/r/)
- [StatMethods](https://www.statmethods.net/)
- [Statistical tools for high-throughput data analysis](http://www.sthda.com/english/)

Two online resources will provide you the solution to the vast majority of your R questions. Getting on those websites is usually the result of a Google search.

- [Statistical Data Analysis R](https://stat.ethz.ch/R-manual/): This resource contains the function manual for R/RStudio including all packages. Example for a function [boxplot](https://stat.ethz.ch/R-manual/R-devel/library/graphics/html/boxplot.html). The most helpful part are the examples at the bottom of the page.
- Stack Overflow: Resources for developers. For example, a Google search for "r ggplot two y axis" may give you the following [result](https://stackoverflow.com/questions/3099219/plot-with-2-y-axes-one-y-axis-on-the-left-and-another-y-axis-on-the-right) Note that all questions on Stack Overflow have to be accompanied by a re-creatable dataset.

Besides many online resources, there are also two useful textbooks

- [Applied Econometrics with R](https://link.springer.com/book/10.1007/978-0-387-77318-6) by Christian Kleiber and Achim Zeileis.
- [Introductory Statistics with R](https://link.springer.com/book/10.1007/978-0-387-79054-1]) by Peter Dalgaard.

An additional online tutorial is [Using R for Introductory Statistics](https://cran.r-project.org/doc/contrib/Verzani-SimpleR.pdf]) by John Verzani.

## Opening RStudio
Work in RStudio is done in four windows:

1. Script Window
     - This is were you type your R Script (.R) and where you execute commands.
     - Comparable to do-file/editor in Stata.
     - This window needs to be opened by File $\Rightarrow$ New File $\Rightarrow$ R Script.
2. Console window
     - Use of R interactively. Should only be used for quick calculations and not part of an analysis.
3. Environment
     - Lists all the variables, data frames, and user-created functions.
     - It is tempting to use the ``Import Dataset'' function \dots Don't.
4. Plots/Packages/Help

There is a base version of R that allows doing many calculations but the power of R comes through its packages. To use functions associated with a particular package, click ``Install'' in the packages window of RStudio and type in the name of the package. Or alternatively, use

- `install.packages("ggplot2")`

To use a package, you have to activate it by either checking the box in the window "Packages" or by including `library(packagename)`. Those packages are updated on a regular basis by users.

The `\#` allows you to include comments in your script file that are not read by R. It is good practice to start any new script with clearing the memory using the command `rm(list=ls())`. Use the command `get()` to determine the current working directory or set the new working directory with the command `setwd()`, e.g., `setwd("E:/")`. For file paths, replace $\backslash$ with $/$. Next, you want to load all libraries necessary for your entire script file with the command `library()`. It is also good practice to save your R-script on a regular basis. The frontmatter, i.e., the top of a R-script file, could look as follows

```{r frontmatter,warning=FALSE}
rm(list=ls())
load("DataAnalysisPAData.RData")
library(openxlsx)
```

### In-class Exercise 1
Create a R-script file with the following components:

1. Two lines for the title and the date (use \#)
2. Clearing all current contents
3. Setting the correct working directory
     - This should be a folder to which you have downloaded all materials.
4. Installing and loading the package `openxlsx`.

## Functions
At the core of R are functions that "do things" based on your input. The basic structure is

- `object = functionname(argument1=value,argument2=value,...)`

The structure has the following components

- `object`: Output of the function will be assigned to object.
- `functionname`: Name of the system function. You can also create and use your own functions. More about this later.
- `argument`: Arguments are function specific.
- `value`: The value you want a particular argument to take.

If a function is executed without an specific assignment, the output will be displayed in the console window. Before using a function, read the documentation. Many functions have default settings. Be aware of default values. In most cases, those defaults are set to values that satisfy most uses. For example, consider the help file for the function [t.test](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/t.test.html). 

-`t.test(x,y=NULL,...,mu=0,conf.level=0.95,...)`

For this function we have the following default values

- `y=NULL`
- `mu=0`
- `conf.level=0.95`

## Data Management

### Data in R

The main data types which can appear in the Environment window of R are:

- Vectors
     - `preselection = seq(1788,2016,4)`
     - `midterm = seq(by=4,to=2018,from=1790)`
- Matrix
     - `somematrix = matrix(8,10,4)`
     - Only numerical values are allowed.
- Data frames
     - By far, the most common data type in R.
     - Comparable to an Excel sheet.
     - More on this later.
- Lists
     - Collection of objects from of various types.
     - `myfirstlist = list(preselection,midterm,somematrix)`

### Data in R


